in:
  type: file
  path_prefix: /Users/kanji.yomoda/Development/play_ground/embulk-output-datastore/test/csv/sample_01.csv.gz
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
  decoders:
  - {type: gzip}
out:
  type: datastore
  project_id: calcium-aria-254518
  auth_method: service_account
  json_keyfile: ./test/credentials.json
  entity: Test
